setxkbmap dvorak es 

patchLocalFiles

xmodmap ~/.config/Xorg/Xmodmap

xrdb ~/.config/Xorg/Xresources

unclutter -idle 2 &

autocutsel -fork &
autocutsel -selection PRIMARY -fork &

urxvtd &

#compton --opengl --vsync opengl-swc --paint-on-overlay -b 

dunst &
udiskie &

wallpaper.sh

exec i3
